inherit_from: .rubocop_todo.yml

require:
- rubocop-rails

Allcops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  StyleGuideBaseURL: https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md
  exclude:
    - vendor/**/*
    - db/**/*
    - bin/**/*
    - config/**/*
Rails:
  Enabled: true

Metrics/Abcsize:
  Max: 25

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false