version: '3.9'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/myapp:cached
      - bundle:/usr/local/bundle
      - /myapp/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    stdin_open: true
    tty: true
    environment:
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
  db:
    image: mysql:5.7.33
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: mysqld --innodb_use_native_aio=0
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444

volumes:
  bundle:
  mysql_data: